# **Laboratorio 2**

In [1]:
from perceptron import Perceptron
from adaline import Adaline

from sklearn.datasets import load_breast_cancer
import pandas as pd

In [2]:
import style
style.mpl_apply()

## Datos 

Los problemas que se van a resolver son los siguientes: AND, XOR y un set de datos provistos por el profesor.

In [ ]:
# Datos de entrada 
AND = [[1, 1],
     [0, 1],
     [1, 0],
     [0, 0]]

T_and= [1, -1, -1, -1]  # Salidas esperadas

In [ ]:
# Datos de entrada 
XOR = [[1, 1],
     [0, 1],
     [1, 0],
     [0, 0]]

T_xor= [1, -1, -1, 1]  # Salidas esperadas

# Perceptron Simple

En esta sección se va a probar la clase `Perceptron` que fue implementada en el script perceptron.py. Se muestran los entrenamientos, ajuste y animacion por iteraciones de los datos AND y XOR.

In [ ]:
# Crear y entrenar el perceptrón
perceptron = Perceptron(AND,T= T_and, learning_rate=0.1, epochs=30, umbral=0.01, weights=[0.5, 0.5], bias=0.5)
perceptron.fit()
perceptron.plot()

In [ ]:
# Crear y entrenar el perceptrón
perceptron = Perceptron(XOR, T =T_xor, learning_rate=0.1, epochs=30, umbral=0.01, weights=[1, 1], bias=-0.5)
perceptron.fit()
perceptron.plot()

Además se muestran los métodos y atributos que se pueden llamar de la clase `Perceptron`.

In [5]:
perceptron.get_bias()

[0.5,
 np.float64(0.4),
 np.float64(0.30000000000000004),
 np.float64(0.20000000000000004),
 np.float64(0.20000000000000004),
 np.float64(0.10000000000000003),
 np.float64(2.7755575615628914e-17),
 np.float64(-0.09999999999999998),
 np.float64(-0.09999999999999998),
 np.float64(-0.19999999999999998),
 np.float64(-0.3),
 np.float64(-0.3)]

In [6]:
perceptron.get_weights()

[array([0.5, 0.5]),
 array([0.5, 0.4]),
 array([0.4, 0.4]),
 array([0.4, 0.4]),
 array([0.4, 0.4]),
 array([0.4, 0.3]),
 array([0.3, 0.3]),
 array([0.3, 0.3]),
 array([0.3, 0.3]),
 array([0.3, 0.2]),
 array([0.2, 0.2]),
 array([0.2, 0.2])]

In [7]:
patrones_que_hicieron_que_ajustara = perceptron.get_malos()  # Número de clasificaciones incorrectas

In [8]:
patrones_que_hicieron_que_ajustara

[[{'coords': array([0, 1]), 'target': -1, 'valor': 1.0, 'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.9, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 0.30000000000000004,
   'y': 1.0}],
 [{'coords': array([0, 1]), 'target': -1, 'valor': 1.0, 'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.9, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 0.30000000000000004,
   'y': 1.0}],
 [{'coords': array([0, 1]), 'target': -1, 'valor': 1.0, 'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.9, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 0.30000000000000004,
   'y': 1.0}],
 [{'coords': array([0, 1]), 'target': -1, 'valor': 1.0, 'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.9, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 0.30000000000000004,
   'y': 1.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.6000000000000001,
   'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.5, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 2.7755575615628914e-17,
   'y': 0.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.6000000000000001,
   'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.5, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 2.7755575615628914e-17,
   'y': 0.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.6000000000000001,
   'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.5, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 2.7755575615628914e-17,
   'y': 0.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.6000000000000001,
   'y': 1.0},
  {'coords': array([1, 0]), 'target': -1, 'valor': 0.5, 'y': 1.0},
  {'coords': array([0, 0]),
   'target': -1,
   'valor': 2.7755575615628914e-17,
   'y': 0.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.20000000000000007,
   'y': 1.0},
  {'coords': array([1, 0]),
   'target': -1,
   'valor': 0.10000000000000006,
   'y': 1.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.20000000000000007,
   'y': 1.0},
  {'coords': array([1, 0]),
   'target': -1,
   'valor': 0.10000000000000006,
   'y': 1.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.20000000000000007,
   'y': 1.0},
  {'coords': array([1, 0]),
   'target': -1,
   'valor': 0.10000000000000006,
   'y': 1.0}],
 [{'coords': array([0, 1]),
   'target': -1,
   'valor': 0.20000000000000007,
   'y': 1.0},
  {'coords': array([1, 0]),
   'target': -1,
   'valor': 0.10000000000000006,
   'y': 1.0}]]

In [9]:
len(patrones_que_hicieron_que_ajustara) #  número de iteraciones realizadas

12

In [10]:
len(patrones_que_hicieron_que_ajustara[2]) #  número de datos mal clasificados la

3

In [11]:
malos_por_iteracion = perceptron.get_malos_por_iteracion()
malos_por_iteracion

[3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 0, 0]

In [12]:
len(malos_por_iteracion)

12

In [13]:
patrones_que_hicieron_que_ajustara[0]

[{'coords': array([0, 1]), 'target': -1, 'valor': 1.0, 'y': 1.0},
 {'coords': array([1, 0]), 'target': -1, 'valor': 0.9, 'y': 1.0},
 {'coords': array([0, 0]),
  'target': -1,
  'valor': 0.30000000000000004,
  'y': 1.0}]

## ADALINE

En esta sección se va a probar la clase `Adaline` que fue implementada en el script adaline.py. Se muestran los entrenamientos, ajuste y animacion por iteraciones de los datos AND y XOR.

In [ ]:
adaline = Adaline(AND, T = T_and, learning_rate=0.1, epochs=1, umbral=0.1, tolerance=1e-36,weights=[1, 1], bias=-0.5)
adaline.fit()
adaline.plot()

In [ ]:
adaline = Adaline(XOR, T = T_xor, learning_rate=0.1, epochs=1, umbral=0.1, tolerance=1e-36,weights=[1, 1], bias=-0.5)
adaline.fit()
adaline.plot()

Adaline tiene la posibilidad de llamar a los mismos metodos y atributos que Perceptron.

In [33]:
adaline.get_weights()

[array([1, 1]), array([1. , 0.8]), array([0.8, 0.8]), array([0.8, 0.8])]

In [34]:
adaline_malos = adaline.get_malos()
adaline_malos[0]  # Datos mal clasificados en la primera iteración

[{'coords': array([0, 1]), 'target': -1, 'valor': 0.5, 'y': 1.0},
 {'coords': array([1, 0]),
  'target': -1,
  'valor': 0.30000000000000004,
  'y': 1.0}]

In [35]:
len(adaline_malos[0])  # número de datos mal clasificados en la primera iteración

2

## Prueba con datos Cáncer de Sklearn.

Crea una tabla donde muestres el porcentaje de instancias clasificadas correctamente para 5 valores diferentes de tasas de aprendizaje y 3 valores de umbral.

In [4]:
data = load_breast_cancer()
df_breast_cancer = pd.DataFrame(data.data, columns=data.feature_names)

In [5]:
pd.set_option('display.max_columns', None)
display(df_breast_cancer)
df_breast_cancer['target'] = data.target
df_breast_cancer.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error,texture error,perimeter error,area error,smoothness error,compactness error,concavity error,concave points error,symmetry error,fractal dimension error,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [6]:
S = df_breast_cancer[['mean radius', 'mean texture']].values  # array de vectores de 2 entradas

# El vector de los targets
T = df_breast_cancer['target'].values

In [8]:
Perceptron = Perceptron(S, T, learning_rate=0.1, epochs=1, umbral=0.1, weights=[.75, 1], bias=-0.5)
Perceptron.fit()
Perceptron.plot()

In [7]:
Adaline = Adaline(S, T, learning_rate=0.1, epochs=1, umbral=0.1, tolerance=1e-36,weights=[.75, 1], bias=-0.5)
Adaline.fit()
Adaline.plot()